#pragma once

#include <font_awesome.h>

#define ICON_SUN       FONT_AWESOME_SUN
#define ICON_MOON      FONT_AWESOME_MOON
#define ICON_LIGHTBULB FONT_AWESOME_BRIGHTNESS
#define ICON_HOME      FONT_AWESOME_HOUSE
#define ICON_LANGUAGE  FONT_AWESOME_GLOBE
#define ICON_WIFI      FONT_AWESOME_WIFI
#define ICON_INFO      FONT_AWESOME_CIRCLE_INFO
#define ICON_CHECK     FONT_AWESOME_CIRCLE_CHECK
#define ICON_LOCATION  FONT_AWESOME_LOCATION_DOT
#define ICON_TRASH     FONT_AWESOME_TRASH
#define ICON_WATER     FONT_AWESOME_CLOUD_RAIN
#define ICON_TEMP      FONT_AWESOME_TEMPERATURE_HALF
#define ICON_UMBRELLA  FONT_AWESOME_CLOUD_SHOWERS_HEAVY
#define ICON_SETTINGS  FONT_AWESOME_GEAR
#define ICON_AIR       FONT_AWESOME_WIND
#define ICON_POWER     FONT_AWESOME_POWER_OFF
#define ICON_BOLT      FONT_AWESOME_CLOUD_BOLT
#define ICON_LEAF      FONT_AWESOME_CLOUD_SUN
#define ICON_DROP      FONT_AWESOME_CLOUD_DRIZZLE
#define ICON_FOG       FONT_AWESOME_CLOUD_FOG
#define ICON_STAR      FONT_AWESOME_STAR
#define ICON_FAN       FONT_AWESOME_WIND

#define ICON_CHART     FONT_AWESOME_CALCULATOR
#define ICON_CONTROL   FONT_AWESOME_POWER_OFF
#define ICON_BACK      FONT_AWESOME_ARROW_LEFT
#define ICON_NEXT      FONT_AWESOME_ARROW_RIGHT
#define ICON_LOCK      FONT_AWESOME_LOCK
#define ICON_UNLOCK    FONT_AWESOME_UNLOCK
#define ICON_SHIELD    FONT_AWESOME_LOCK
#define ICON_SERVER    FONT_AWESOME_SD_CARD
#define ICON_HANGER    FONT_AWESOME_ARROWS_REPEAT
#define ICON_WINDOW    FONT_AWESOME_CLOUD
#define ICON_FIRE      FONT_AWESOME_TRIANGLE_EXCLAMATION
#define ICON_PLUG      FONT_AWESOME_LINK
#define ICON_VOLUME    FONT_AWESOME_VOLUME_HIGH
#define ICON_GLOBE     FONT_AWESOME_GLOBE
#define ICON_REFRESH   FONT_AWESOME_ARROWS_ROTATE
#define ICON_KEYBOARD  FONT_AWESOME_CALCULATOR
#define ICON_LIST      FONT_AWESOME_CIRCLE_INFO
#define ICON_USER      FONT_AWESOME_USER
